### PR TITLE
My first Pull Request 

### PR DESCRIPTION
**Pull request by david63011**
I changed the header of the HTML to say Hello Microverse

and I changed the CSS to style this greeting

### CODE REVIEW

**Review by Ismailco — CHANGES_REQUESTED** [review]
### Hi @david63011, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
#### I will add here the required changes because I can't use the inline Comments (no changes have been made)

- [ ] Linter should be set up correctly for this repository, kindly use the HTML&CSS linters in this repo
- [ ] README file should be descriptive, kindly consider using the README template provided by microverse
- [ ] Pull Request should have a summary describing introduced changes in more detail, kindly consider adding a description to this PR with the changes you made
- [ ] There should be a `.gitignore` file listing `test.md` file and `node_modules` directory, kindly consider creating a `.gitignore` file in this branch and add these file and directory to it

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by david63011** [comment]
Hi,
I added style lint to the CSS and used a HTML web to link the HTML
I updated the readme
I updated the comments 
and I added gitignore that listed the test.md and the node modules

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @david63011 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good use of GitHub flow :heavy_check_mark: 

 ## Required Changes ♻️

- [ ]  I noticed that you have a lot of empty files because you missed the project requirements Please follow carefully [the project requirements ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md). It is very important for the developer to peer attention to detail a give a completed project :smile: 
- [ ] Please add the `node_modules` directory and `test.md` to the .gitignore file. It's a good practice to add the node_modules to the .gitignore. It will help you to avoid a big size of dependencies in your repository. :smile:  
- [ ] Please add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project in order to make your project more professional :+1: 
- [ ] Please set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git. Linter will help you to fix some errors and follow best practices:+1: 
- [ ] Please make your Pull Request to make it a more descriptive t, it should tell what changes are inside to the reviewer. A good example will be **Set up a Hello Microverse project** instead of  **My first pull request **  :+1: 
- [ ] Please edit also your Pull Request summary because like your PR title the summary should describe introduced changes in more detail. :+1: 
You can check the example below :arrow_down: 
Screenshot from 2022-08-16 18-25-08


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by david63011** [comment]
I dont understand I added node_modules directory and test.md to the .gitignore file. 
I used lintor 
i added a descriptive readMe
i updated the pull request

**Comment by codecaiine** [comment]
Hi @david63011, Please check the screenshots related to your project. You can see that a lot of requirements are missing. 
You can see that there are no linters , and Node modules are not ignored... 
I would like to recommend you Please carefully [the project requirements ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md). It is very important for the developer to peer attention to detail a give a completed project smile:+1: 
Screenshot from 2022-08-17 01-43-07
Screenshot from 2022-08-17 01-43-00

**Comment by codecaiine** [comment]
If you need any help please let me know I will try my best to be available  :+1:

**Comment by david63011** [comment]
that is what i dont understand i updated the readme and pushed it the same
with the gitignore... on my repo they are updated

**Comment by bellom** [comment]
Hello @david63011 👋,

This is an additional review as a result of the second opinion request.

I noticed you name your gitignore file wrongly, try `.gitignore` instead of `gitignore`. 

It is very important to go through the [project requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) carefully, and check it line by line.

Please ask for another review once you're done with the implementation.

Kindly tag me here if you still need help.

Keep rocking 🚀!

**Pull request closed without merging**
